version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=-*@%-6yig5ba#=ic882k^t9j8xefz%o#_5gu8bw8l=h+*xy!#&
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/varlib/postgresql/data
volumes:
  postgres_data: